name: Zurna Search APK Yapıcı
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build with Buildozer
        uses: Peter-Smyth/buildozer-action@v1
        with:
          buildozer_version: master
